### ISSUE TITLE
DC input voltage incorrect

### ISSUE THREAD

**Issue by River-Mochi** [joric/pinecil#12]
Using Ble page today 

1. plugged into simple 20V charger: Pinepower portable usb-C PD65W, 20V.
2. Pinecil screen shows the correct 20v.
3. using beta IronOS  firmware  "More Unique"  2.20.EB5D6EA  18-02-23
4. BLE page  shows **35-36V**  for  Pinecil - 1    and  **25-26V** for my second Pinecil -2
![image](https://user-images.githubusercontent.com/97197236/220228763-7d9c9c53-b5a2-47a0-81c7-5a80629189c0.png)
![image](https://user-images.githubusercontent.com/97197236/220228776-bcb511fa-d8d8-4441-ae2a-584ba400a791.png)

5. Got another normal 20V charger with USB-C.  also showing correctly 20V on Pinecil  screen 
On the BLE webpage, shows 25V when I didnt have heat on but kept climbing up higher and higher. was up to 29V by time I took this screen capture. 
![image](https://user-images.githubusercontent.com/97197236/220229352-630979ef-9cc1-46f3-8ec1-1da362020e66.png)

I don't think it is my Pinecils since both are showing the same things on  BLE webpage.  the Voltage should be  20V and not higher like this.

**Comment by scythefwd** [comment]
Seeing 24v (and it slowly creeps up about .1 degree about every 16 seconds, give or take).  Pine power showing 19.9v.  My power meter is showing 20.05V.  

![image](https://user-images.githubusercontent.com/62770684/220524894-a48f4cc0-99d7-442e-9b09-056808d67640.png)

Refreshing the site drops Voltages down to 0V for a couple seconds, it reconnects, and jumps right back up to where it was before the refresh once I re-pair the device.

**Comment by River-Mochi** [comment]
I just rolled back from the newest  Pinecil BLE  to really old November 2022 one and  the voltage displays correctly. 
I think  IronOS changed  some things with BLE or other things now and some information sent to BLE may need to be looked at. 

- If you have time @joric  would you mind checking the info coming from Pinecil now since it seems to have affected this app. 
newest Beta in IronOS has BLE in it since there is no more BLE branch.
- next 2.21 stable release will have BLE in it so people do not have to install a separate app anymore. this is the newest beta BLE I tested and BLE works on it with the other BLE app.  this is dated Feb 18, 2023  and has some BLE changes in it that is affecting the data shown on this Repo.
https://github.com/Ralim/IronOS/actions/runs/4219016732

Temperature changing also does not work with newest IRonOS BLE beta  and bLE webpage  (and this will be what is going to be released with all 2.21 firmware).
