### ISSUE TITLE
add image of api

### ISSUE THREAD

**Issue by River-Mochi** [joric/pinecil#14]
- suggest Add image of app to main Readme or the Wiki page so people see an example on main Readme  page
- sometimes a nice image encourages people to try it.
- add **Discussions** section to this repo as some things are not issues so much as discussions on different BLE GATT options or work arounds to explore other BLE apps for Pinecil V2.

![image](https://user-images.githubusercontent.com/97197236/221750642-1f39338d-9e32-4dc9-9fbc-a562f2e057ee.png)

**Comment by joric** [comment]
Way ahead of ya, it's in og media properties when you publish link to project in wiki, see https://twitter.com/joric/status/1602831534674821121 for example. Also I don't do big readmes, I do wikis because I don't like garbage commits in the main repository.

**Comment by River-Mochi** [comment]
> Way ahead of ya, it's in og media properties when you publish link to project in wiki, see https://twitter.com/joric/status/1602831534674821121 for example. Also I don't do big readmes, I do wikis because I don't like garbage commits in the main repository.

I don't use twitter so I did not see it.  why not put image inside the wiki  github page here, would just be nice to see image of this github so people get idea what it is to try it out.  if it's on _Twitter_ some people don't have this other app or stopped using it this year; they come to github wiki page though.
just a suggestion. I understand if you only want image in twitter and not the wiki repo.

**Comment by joric** [comment]
There is an image don't you see it?

https://github.com/joric/pinecil/wiki

![image](https://user-images.githubusercontent.com/852547/222990415-e2fc222f-8dcc-4953-befe-2dbd0207e8e4.png)

**Comment by River-Mochi** [comment]
> There is an image don't you see it?

oh yes thanks I see  now that I go to wiki page.  the photo with pinecil in the hand in front of screen :)
