### ISSUE TITLE
IronOS changing to 128 bit UUID

### ISSUE THREAD

**Issue by River-Mochi** [joric/pinecil#15]
Change to 128bit UUID's #1608  is now  merged into IRonOS  beta ( coming in the next release)

Please check if it doesn't break  Ble webpage.
Original ticket explaining the reason for 128bit UUID:  Original ticket explaining the reasons for UUID change to 128bit: https://github.com/Ralim/IronOS/issues/1569

**Zip file is here for Download** of the beta:
https://github.com/Ralim/IronOS/actions/runs/4420347769

**Comment by joric** [comment]
> https://github.com/Ralim/IronOS/actions/runs/4420347769

This one is broken, there's no exposed services in BLE Explorer even.

**Comment by River-Mochi** [comment]
it's broken in PineSAM too please report that on comments for it so Ralim knows :)
he did ask for people to test it in his comments, so now we have tested it.
comments to the PR not working are here:  https://github.com/Ralim/IronOS/pull/1608
