### ISSUE TITLE
wiki  page  could use new links to  stable 2.21  BLE  and also newest BLisp  updater.

### ISSUE THREAD

**Issue by River-Mochi** [joric/pinecil#17]
Now that  2.21 stable with BLE  is released,  the joric wiki page  link for BLE FW could be updated to 

- here:  https://github.com/Ralim/IronOS/releases

The link for Blisp  might also need updating; gamiee said there are problems with older blisp as it can fail for the larger  Ble firmware size. 

- Newest Blist release  for all Windows/Linux/MacOS  is here (Jan 21, 2023)
- https://github.com/pine64/blisp/releases/tag/v0.0.3

![image](https://user-images.githubusercontent.com/97197236/230786718-58fca333-92c1-429c-9887-d69857aa6f00.png)

**Comment by joric** [comment]
added
