### ISSUE TITLE
Corrections for new IronOS version

### ISSUE THREAD

**Issue by ithinkido** [joric/pinecil#19]
There have been some changes to the BLE UUIDS in the latest version of IronOS.  These break the current code as tested on a Linux macine using Chrome browser
![image](https://github.com/joric/pinecil/assets/52834821/b5e01e28-f227-4e47-98d5-d4b9db4490b4)

It also seems like the values for handle tamp and DC input voltage are swapped.

**Comment by joric** [comment]
fixed in #20
