### ISSUE TITLE
Error after connecting Pinecil (V2 IronOs v2.22) "No Services matching UUID"

### ISSUE THREAD

**Issue by globus243** [joric/pinecil#21]
Device: PinecilV2 
OS: IronOS 2.22

After clicking "pair" and selecting the Pinecil, nothing happens, in the Developer Tool's console I can the the following messages:
```
Requesting any Bluetooth Device...
pinecil/:223 > Requested Pinecil-22104EC (XXXXXX)
pinecil/:368 [11:42:34] Connecting to Bluetooth Device... 
pinecil/:297 > Bluetooth Device connected.
pinecil/:320 DOMException: No Services matching UUID f6d75f91-5a10-4eba-a233-47d3f26a907f found in Device.
pinecil/:335 DOMException: No Services matching UUID 9eae1adb-9d0d-48c5-a6e7-ae93f0ea37b0 found in Device.
```

I downloaded an older version of the HTML file, without the changes from [this PR](https://github.com/joric/pinecil/pull/20) and that worked fine. For sanity I re-flashed my Pinecil with v2.22 through pineflash again, to be sure, and the issue persisted.

**Comment by joric** [comment]
reverted in #22
