### ISSUE TITLE
Newer BLE beta IronOS available, several BLE changes in it

### ISSUE THREAD

**Issue by River-Mochi** [joric/pinecil#7]
thought you might be interested in the new February 2023 BLE betas.

newer BLE betas are available on Ralim's IronOS (the one linked in this github is old from Nov. 2022).

For example, this is newest beta from today, has BLE in  it : https://github.com/Ralim/IronOS/actions/runs/4190920103
[Pinecilv2_EN.zip](https://github.com/joric/pinecil/files/10762818/Pinecilv2_EN.zip)
date of this beta is Feb 16,2023.

1. Ralim last week implemented Advanced Menu feature that allows people to check a box to turn on/off  BLE. This will make it easier so people won't have to load two separate firmware when 2.21 release comes out. (you can see this feature in the linked I gave above). reference this older ticket (https://github.com/Ralim/IronOS/issues/1495)
2. BLE will not broadcast the same Pinecil name in the future, it will be unique name for people who have multiple pinecils in the same room.  implemented from this ticket request  (https://github.com/Ralim/IronOS/issues/1545)
example of Unique name Pinecil-number (I was still able to pair with BLE webpage).
![image](https://user-images.githubusercontent.com/97197236/219539205-a7dcfa18-8acd-463e-884f-7e85c3b95993.png)

3. Some open tickets for other BLE changes coming, such as the UUID. (https://github.com/Ralim/IronOS/issues/1569)

1  and 2 are done in the newest beta, but not 3.

**Comment by joric** [comment]
Okay cool. I don't have time really (acknowledged comment). Thanks for the info I'm looking forward to it.
