### ISSUE TITLE
Light version no longer shows with white background

### ISSUE THREAD

**Issue by River-Mochi** [joric/pinecil#8]
Light version no longer shows with white background.
both light and dark have a black background now.

**Comment by joric** [comment]
Well that was your PR, did you want it merged?

**Comment by River-Mochi** [comment]
I'm not sure what you mean by merged, but when I go here I get black background on Android phone and also windows PC and I thought this one was the "Light" choice.
https://joric.github.io/pinecil/

![image](https://user-images.githubusercontent.com/97197236/219795741-8fa08079-c135-4cd3-b80e-0c8081bdf953.png)

I actually like the white background better, asked for dark choice only if it would be easy for you and some other people like dark background for choice. (me, I liked the white one and colors you had original :)

**Comment by joric** [comment]
Oh it wasn't you, sorry. https://github.com/joric/pinecil/pull/4

**Comment by joric** [comment]
I'll reverse it, I didn't like it either.

**Comment by River-Mochi** [comment]
thank-you, it's back to being Light with white background. easier to see things now.
